### ISSUE TITLE
旋转算法的失败

### ISSUE THREAD

**Issue by StormGens** [zhuofengli/AndroidNDKImageProcessing#1]
经我测试，当我添加一个需要旋转180°的图片的时候，旋转失败，而当我添加一个需要旋转270°的图片时候，发生本地方法（native）错误。我不太懂c，但是我尝试进去看了代码。我发现以下情况：
 switch(orientation)
    {
        case 1:
        {
            ret = rotate90(pix, targetW, targetH);
            break;
        }

```
    case 2:
    {
        ret = rotate180(pix, &targetW, targetH);
        break;
    }

    case 3:
    {
        ret = rotate270(pix, &targetW, targetH);
        break;
    }

    default:
        break;
}
```

于是我尝试将三种情况的参数都改为ret = rotateXXX(pix, targetW, targetH);
去掉了case 2和case 3中的&符号，试了一下就好了。不过不懂什么原因，也不知道是不是有潜在bug。
还是希望原作者更正。

**Comment by zhuofengli** [comment]
你好，

是我的rotate90那一行写错了，
按我的原意的话，应该是ret = rotateXX(pix, &targetW, &targetH); 

targetW和targetH前面都应该加&

按照你的改法的话，不改rotateXXX函数内部的话，应该是有问题的。

你试试都加上&，测试一下你的图片

**Comment by StormGens** [comment]
谢谢作者出现，我之前之所以那样改，是因为我发现只有旋转90°是好使的，所以都改成和90°的一样。按照你的改法重新编译运行后，凡是调用了反转方法的都是不可用了，就算我强行停止后启动，也只有180°的勉强可用一次(但是方向没有得到旋转，是头朝下的)。之后就要吗本地方法错误，要吗程序就自动退出了。而按照我乱改的反而会好点，就怕出什么不可预知问题。希望作者有空可以调试测试修正下。万分感谢。
注：手机Galaxy S3（i9300），我四个方向各拍照一张用来测试添加。

**Comment by zhuofengli** [comment]
能给我几张你的测试图片吗，我邮箱zhuofengli@gmail.com

**Comment by StormGens** [comment]
众所周知原因，发送邮件失败，已经上传到网络空间，其中压缩文件是那四张图片打的包。
http://pan.baidu.com/share/link?shareid=488230&uk=1678217510
https://www.dropbox.com/sh/2lg1ikac2ywsry8/oQXICGqsRH

**Comment by zhuofengli** [comment]
Hi stormGens，不好意思，确实之前的错误就是&，去掉就好了，我已经commit了纠正过的版本，谢谢report！

**Comment by StormGens** [comment]
You Help me，I help you，we help each other。谢谢楼主zhuofengli提供的代码。 Thanks，thanks ，thanks，thanks，zhuofengli !(改编自张国荣Monica，嘿嘿)。

**Comment by zhuofengli** [comment]
哈哈，国荣哥，不客气
